version: "2"

checks:
  method-lines:
    enabled: false

plugins:
  editorconfig:
    enabled: true
    config:
      editorconfig: .editorconfig
  stylelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 70

## other configuration excluded from example...
exclude_patterns:
- "static/"
- "grunt/"
- "spec/"
- "**/vendor/"
